### ISSUE TITLE
[Critical] No Order found in vendor page! No vendor assigned in order

### ISSUE THREAD

**Issue by ManigandanRaamanathan** [weDevsOfficial/dokan#293]
@sabbir1991  @tareq1988  @saimonh3  Very critical problem. When the customer create order products of a particular type of vendor, the system sends email notifications to both admin and the product vendor upon successful order placement. But the order only appears on the admin panel and it is not appearing on the vendors page.
The vendor name for the order always set as admin user "user" instead of the vendor name but it is sending email notifications to the vendor upon new orders owned by them.

This below highlighted are the new order placed (contains vendor's product). But the vendor names always stays as "user" instead of the actual vendor name. (And once moving the administrator account, the new order vendor's become empty. )
![capture4](https://user-images.githubusercontent.com/22089729/41808465-786c0928-7710-11e8-83d2-5880cfa42f6f.PNG)

The below items in the order is belongs to a particular vendor named "Tepanyaki Cafe"
![capture5](https://user-images.githubusercontent.com/22089729/41808497-d0680e88-7710-11e8-87a8-11bf499d59cd.PNG)

The below items proof that belong to the vendor.
![capture9](https://user-images.githubusercontent.com/22089729/41808596-7da8d554-7712-11e8-932f-29507354ef47.PNG)

But the vendor's page always shows no order found.
![capture8](https://user-images.githubusercontent.com/22089729/41808587-5adc1572-7712-11e8-9da3-da37acd26d9e.PNG)

Please help me fix this bug

**Comment by ManigandanRaamanathan** [comment]
The products in the order is owned by the vendor. But it always setting the vendor as "user" the admin. And not showing the orders in the vendors page.

**Comment by ManigandanRaamanathan** [comment]
Tried removing the particular admin "user". But still there is no any changes. All new orders appearing in the admin order box but still not showing them in the vendor profile that owned that item. But the system emails the particular vendor when they receive new orders. But not showing the orders in their panel.
* I'm using woocommerce rest api to create new orders.

**Comment by sabbir1991** [comment]
Hi, 
I am checking all things. I didn't get any issues. Please check this video. 

https://www.useloom.com/share/3c644ebc5b1b4591b56780d96838dbc7

**Comment by ManigandanRaamanathan** [comment]
Did you try it using rest api?

**Comment by ManigandanRaamanathan** [comment]
Can you give me the manual code to manually assign the vendor when creating new order using rest api?

**Comment by sabbir1991** [comment]
We didn't provide any route to create an order manually for the vendor. Because it's handle dokan internally. If you need to create or assign order manually for a vendor then please check this `includes/order-functions.php` file. You can understand how dokan can split order automatically when a customer places an order.

**Comment by ManigandanRaamanathan** [comment]
Do I need to copy the codes and paste it in the woocommerce rest api codes? Any idea to inject or make the system run again the function to identify vendors?

**Comment by ManigandanRaamanathan** [comment]
I have checked the order-functions.php. but it contains functions to fetch orders assigned to the vendors only. But the problem here is that the system is not assigning the particular vendor when creating the order itself. If the system dont assign the vendor on the order the vendor wont be able to see the order in their dashboard. So can you get me a code to forcefully check and assign vendors to new orders creation via woocommerce via rest api*??

**Comment by ManigandanRaamanathan** [comment]
@sabbir1991  couldyou please explain about the plugin "dokan - custom seller order plugin" that you used in your wordpress? Will it fix the issues I'm having?

**Comment by sabbir1991** [comment]
Actually, this is not an official plugin. This is a test purpose customization plugin developed by myself.
By the way, your order splitting problem via REST API has been fixed in version 2.8.2. Please update your plugin and check again.

Thanks

**Comment by ManigandanRaamanathan** [comment]
Thanks a lot for the rest api support update. I will try it and let you know the result as soon as possible.

**Comment by ManigandanRaamanathan** [comment]
Now it assigning the order to the particular vendor in the admin page. But it is still not shown in the vendor page.

Below shows order is being assigned to the vendor, but not shown in the vendor page:-
![capture15](https://user-images.githubusercontent.com/22089729/41900523-8703c0d6-7961-11e8-9113-319cce4dcc7a.PNG)

![capture16](https://user-images.githubusercontent.com/22089729/41900535-8c0fd8f8-7961-11e8-8d3d-889580d4abaa.PNG)

**Comment by saimonh3** [comment]
@ManigandanRaamanathan Thanks for noticing it, it will be fixed on the next update. For now you can just place these code on maybe_split_orders method ( dokan/includes/class-order-manager.php line no: 154 )
```
            $parent_order->save();

            // if the request is rest api then insert the order data to sync table
			if ( defined( 'REST_REQUEST' ) ) {
				do_action( 'dokan_checkout_update_order_meta', $parent_order_id, $seller_id );
			}

            return;

```

**Comment by ManigandanRaamanathan** [comment]
Thanks for the fix code. Will try and update you.

**Comment by ManigandanRaamanathan** [comment]
Works perfectly fine. Thanks for the rapid support.

**Comment by datdotien99** [comment]
> @ManigandanRaamanathan Thanks for noticing it, it will be fixed on the next update. For now you can just place these code on maybe_split_orders method ( dokan/includes/class-order-manager.php line no: 154 )
> 
> ```
>             $parent_order->save();
> 
>             // if the request is rest api then insert the order data to sync table
> 			if ( defined( 'REST_REQUEST' ) ) {
> 				do_action( 'dokan_checkout_update_order_meta', $parent_order_id, $seller_id );
> 			}
> 
>             return;
> ```

@saimonh3 I am on dokan version 3.9.4, currently I check in Manager.php (dokan-lite/includes/Order) there is this code, but the vendor's cart has not been updated when there is an order.

**Comment by nurul-umbhiya** [comment]
@datdotien99 would be great if you create a support ticket for this. thanks.

**Comment by datdotien99** [comment]
@nurul-umbhiya Please show me how to create a ticket and where it is located . Thank you so much
